packages:
  - apps/*
  - packages/*
  - packages/runtimed-node/npm/*
  - plugins/nteract/*

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-free'
  - esbuild
minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.16
  vite-plus: 0.1.16
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  '@codemirror/language': 6.12.2
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
