//! TypeScript bindings generated from the notebook protocol surface.
//!
//! The generator intentionally emits the frontend-facing request discriminator
//! as `type` even though Rust serializes requests with `action`; the Tauri
//! transport translates `type` to `action` when it builds
//! `NotebookRequestEnvelope`.

use std::path::{Path, PathBuf};

const GENERATED_HEADER: &str = "// @generated by cargo run -p notebook-protocol --bin generate-runtimed-types\n// Do not edit by hand.\n\n";

pub const NOTEBOOK_REQUEST_TYPES: &[&str] = &[
    "launch_kernel",
    "execute_cell",
    "execute_cell_guarded",
    "interrupt_execution",
    "shutdown_kernel",
    "run_all_cells",
    "run_all_cells_guarded",
    "send_comm",
    "get_history",
    "complete",
    "save_notebook",
    "clone_as_ephemeral",
    "sync_environment",
    "approve_trust",
    "approve_project_environment",
    "get_doc_bytes",
    "create_blob_upload",
    "complete_blob_upload",
    "abort_blob_upload",
];

pub const NOTEBOOK_RESPONSE_RESULTS: &[&str] = &[
    "kernel_launched",
    "kernel_already_running",
    "cell_queued",
    "interrupt_sent",
    "kernel_shutting_down",
    "no_kernel",
    "guard_rejected",
    "all_cells_queued",
    "notebook_saved",
    "save_error",
    "notebook_cloned",
    "ok",
    "error",
    "history_result",
    "completion_result",
    "sync_environment_complete",
    "sync_environment_failed",
    "doc_bytes",
    "blob_stored",
    "blob_upload_created",
    "blob_upload_part_ack",
    "blob_upload_error",
];

pub const SESSION_CONTROL_TYPES: &[&str] = &["sync_status"];
pub const NOTEBOOK_DOC_PHASES: &[&str] = &["pending", "syncing", "interactive"];
pub const RUNTIME_STATE_PHASES: &[&str] = &["pending", "syncing", "ready"];
pub const INITIAL_LOAD_PHASES: &[&str] = &["not_needed", "streaming", "ready", "failed"];

fn quoted_array(values: &[&str], indent: &str) -> String {
    values
        .iter()
        .map(|value| format!("{indent}\"{value}\","))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn generated_request_types_ts() -> String {
    format!(
        r#"{GENERATED_HEADER}import type {{ QueueEntry }} from "./runtime-state";

export interface GuardedNotebookProvenance {{
  observed_heads: string[];
}}

export interface DependencyGuard {{
  observed_heads: string[];
}}

export type PackageManager = "uv" | "conda" | "pixi" | (string & {{}});

export type EnvSource =
  | `${{PackageManager}}:prewarmed`
  | `${{PackageManager}}:inline`
  | "uv:pyproject"
  | "pixi:toml"
  | "conda:env_yml"
  | `${{PackageManager}}:pep723`
  | "deno"
  | (string & {{}});

export type LaunchSpec = "auto" | "" | "prewarmed" | `auto:${{PackageManager}}` | EnvSource;

export interface FeatureFlags {{
  bootstrap_dx?: boolean;
}}

export interface DenoLaunchedConfig {{
  permissions: string[];
  import_map?: string | null;
  config?: string | null;
  flexible_npm_imports: boolean;
}}

export interface LaunchedEnvConfig extends FeatureFlags {{
  uv_deps?: string[] | null;
  conda_deps?: string[] | null;
  conda_channels?: string[] | null;
  pixi_deps?: string[] | null;
  pixi_toml_deps?: string[] | null;
  pixi_toml_path?: string | null;
  pyproject_path?: string | null;
  environment_yml_path?: string | null;
  environment_yml_deps?: string[] | null;
  deno_config?: DenoLaunchedConfig | null;
  venv_path?: string | null;
  python_path?: string | null;
  launch_id?: string | null;
  prewarmed_packages?: string[];
}}

export interface CommRequestMessage {{
  header: Record<string, unknown>;
  parent_header?: Record<string, unknown> | null;
  metadata?: Record<string, unknown>;
  content: Record<string, unknown>;
  buffers: number[][];
  channel: string;
}}

export interface BlobUploadPart {{
  part_number: number;
  sha256: string;
  size: number;
}}

export type NotebookRequest =
  | {{
      type: "launch_kernel";
      kernel_type: string;
      env_source: LaunchSpec;
      notebook_path?: string | null;
    }}
  | {{ type: "execute_cell"; cell_id: string }}
  | {{ type: "execute_cell_guarded"; cell_id: string; observed_heads: string[] }}
  | {{ type: "interrupt_execution" }}
  | {{ type: "shutdown_kernel" }}
  | {{ type: "run_all_cells" }}
  | {{ type: "run_all_cells_guarded"; observed_heads: string[] }}
  | {{ type: "send_comm"; message: CommRequestMessage }}
  | {{
      type: "get_history";
      /** Glob-style pattern to match. null for no filter. */
      pattern: string | null;
      /** Maximum number of entries to return. */
      n: number;
      /** Deduplicate identical entries when true. */
      unique: boolean;
    }}
  | {{ type: "complete"; code: string; cursor_pos: number }}
  | {{
      type: "save_notebook";
      /** Format code cells before writing to disk. */
      format_cells: boolean;
      /** Target path. Omit or null to save in place. */
      path?: string | null;
    }}
  | {{ type: "clone_as_ephemeral"; source_notebook_id: string }}
  | {{ type: "sync_environment"; guard?: DependencyGuard | null }}
  | {{ type: "approve_trust"; observed_heads?: string[] | null }}
  | {{ type: "approve_project_environment"; project_file_path?: string | null }}
  | {{ type: "get_doc_bytes" }}
  | {{
      type: "create_blob_upload";
      media_type: string;
      size: number;
      sha256?: string | null;
      part_size?: number | null;
      purpose?: string | null;
    }}
  | {{ type: "complete_blob_upload"; upload_id: string; parts: BlobUploadPart[] }}
  | {{ type: "abort_blob_upload"; upload_id: string }};

/** One entry returned by `get_history`. */
export interface HistoryEntry {{
  session: number;
  line: number;
  source: string;
}}

/** One item returned in a `completion_result`. */
export interface CompletionItem {{
  label: string;
  kind?: string | null;
  detail?: string | null;
  source?: string | null;
}}

export type NotebookResponse =
  | {{
      result: "kernel_launched";
      kernel_type: string;
      env_source: EnvSource;
      launched_config: LaunchedEnvConfig;
    }}
  | {{
      result: "kernel_already_running";
      kernel_type: string;
      env_source: EnvSource;
      launched_config: LaunchedEnvConfig;
    }}
  | {{ result: "cell_queued"; cell_id: string; execution_id: string }}
  | {{ result: "interrupt_sent" }}
  | {{ result: "kernel_shutting_down" }}
  | {{ result: "no_kernel" }}
  | {{ result: "guard_rejected"; reason: string }}
  | {{ result: "all_cells_queued"; queued: QueueEntry[] }}
  | {{ result: "notebook_saved"; path: string }}
  | {{ result: "save_error"; error: SaveErrorKind }}
  | {{ result: "notebook_cloned"; notebook_id: string; working_dir?: string | null }}
  | {{ result: "ok" }}
  | {{ result: "error"; error: string }}
  | {{ result: "history_result"; entries: HistoryEntry[] }}
  | {{
      result: "completion_result";
      items: CompletionItem[];
      cursor_start: number;
      cursor_end: number;
    }}
  | {{ result: "sync_environment_complete"; synced_packages: string[] }}
  | {{ result: "sync_environment_failed"; error: string; needs_restart: boolean }}
  | {{ result: "doc_bytes"; bytes: number[] }}
  | {{ result: "blob_stored"; hash: string; size: number; media_type: string }}
  | {{ result: "blob_upload_created"; upload_id: string; part_size: number; expires_at: string }}
  | {{ result: "blob_upload_part_ack"; upload_id: string; part_number: number; sha256: string }}
  | {{ result: "blob_upload_error"; reason: BlobUploadErrorKind }};

/**
 * Structured save failures returned in `NotebookResponse::SaveError`.
 * Mirrors `notebook_protocol::protocol::SaveErrorKind`.
 */
export type SaveErrorKind =
  | {{
      type: "path_already_open";
      /** UUID of the room that currently holds this path. */
      uuid: string;
      /** The conflicting path. */
      path: string;
    }}
  | {{ type: "io"; message: string }};

export type BlobUploadErrorKind =
  | {{ kind: "size_mismatch" }}
  | {{ kind: "hash_mismatch" }}
  | {{ kind: "over_cap" }}
  | {{ kind: "unknown_upload" }}
  | {{ kind: "invalid_header" }}
  | {{ kind: "unsupported" }}
  | {{ kind: "io"; message: string }};
"#
    )
}

pub fn generated_protocol_contract_ts() -> String {
    format!(
        r#"{GENERATED_HEADER}import type {{
  InitialLoadPhase,
  NotebookDocPhase,
  RuntimeStatePhase,
  SessionStatus,
}} from "./handle";
import type {{ NotebookRequest, NotebookResponse }} from "./request-types";

type MissingUnionMember<Union extends string, Values extends readonly string[]> = Exclude<
  Union,
  Values[number]
>;

export const NOTEBOOK_REQUEST_TYPES = [
{}
] as const satisfies readonly NotebookRequest["type"][];

export const NOTEBOOK_REQUEST_TYPES_EXHAUSTIVE: MissingUnionMember<
  NotebookRequest["type"],
  typeof NOTEBOOK_REQUEST_TYPES
> extends never
  ? true
  : never = true;

export const NOTEBOOK_RESPONSE_RESULTS = [
{}
] as const satisfies readonly NotebookResponse["result"][];

export const NOTEBOOK_RESPONSE_RESULTS_EXHAUSTIVE: MissingUnionMember<
  NotebookResponse["result"],
  typeof NOTEBOOK_RESPONSE_RESULTS
> extends never
  ? true
  : never = true;

export type SessionControlMessage = {{ type: "sync_status" }} & SessionStatus;

export const SESSION_CONTROL_TYPES = [
{}
] as const satisfies readonly SessionControlMessage["type"][];

export const NOTEBOOK_DOC_PHASES = [
{}
] as const satisfies readonly NotebookDocPhase[];

export const NOTEBOOK_DOC_PHASES_EXHAUSTIVE: MissingUnionMember<
  NotebookDocPhase,
  typeof NOTEBOOK_DOC_PHASES
> extends never
  ? true
  : never = true;

export const RUNTIME_STATE_PHASES = [
{}
] as const satisfies readonly RuntimeStatePhase[];

export const RUNTIME_STATE_PHASES_EXHAUSTIVE: MissingUnionMember<
  RuntimeStatePhase,
  typeof RUNTIME_STATE_PHASES
> extends never
  ? true
  : never = true;

export const INITIAL_LOAD_PHASES = [
{}
] as const satisfies readonly InitialLoadPhase["phase"][];

export const INITIAL_LOAD_PHASES_EXHAUSTIVE: MissingUnionMember<
  InitialLoadPhase["phase"],
  typeof INITIAL_LOAD_PHASES
> extends never
  ? true
  : never = true;

export const DISPLAY_CAPABLE_JUPYTER_OUTPUT_TYPES = ["execute_result", "display_data"] as const;

export type DisplayCapableJupyterOutputType = (typeof DISPLAY_CAPABLE_JUPYTER_OUTPUT_TYPES)[number];

export interface DisplayCapableJupyterOutput {{
  output_type: DisplayCapableJupyterOutputType;
  data: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  execution_count?: number | null;
  display_id?: string;
}}

export function isDisplayCapableJupyterOutputType(
  outputType: unknown,
): outputType is DisplayCapableJupyterOutputType {{
  return outputType === "execute_result" || outputType === "display_data";
}}

export function isDisplayCapableJupyterOutput<T extends {{ output_type: unknown }}>(
  output: T,
): output is Extract<T, {{ output_type: DisplayCapableJupyterOutputType }}>;
export function isDisplayCapableJupyterOutput(
  output: unknown,
): output is DisplayCapableJupyterOutput;
export function isDisplayCapableJupyterOutput(
  output: unknown,
): output is DisplayCapableJupyterOutput {{
  return (
    typeof output === "object" &&
    output !== null &&
    isDisplayCapableJupyterOutputType((output as {{ output_type?: unknown }}).output_type)
  );
}}

export function isInitialLoadFailed(
  initialLoad: InitialLoadPhase,
): initialLoad is Extract<InitialLoadPhase, {{ phase: "failed" }}> {{
  return initialLoad.phase === "failed";
}}

export function isInitialLoadStreaming(
  initialLoad: InitialLoadPhase,
): initialLoad is Extract<InitialLoadPhase, {{ phase: "streaming" }}> {{
  return initialLoad.phase === "streaming";
}}
"#,
        quoted_array(NOTEBOOK_REQUEST_TYPES, "  "),
        quoted_array(NOTEBOOK_RESPONSE_RESULTS, "  "),
        quoted_array(SESSION_CONTROL_TYPES, "  "),
        quoted_array(NOTEBOOK_DOC_PHASES, "  "),
        quoted_array(RUNTIME_STATE_PHASES, "  "),
        quoted_array(INITIAL_LOAD_PHASES, "  "),
    )
}

fn workspace_root() -> std::io::Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "notebook-protocol manifest is not under a workspace crates directory",
            )
        })
}

pub fn write_generated_files() -> std::io::Result<()> {
    let root = workspace_root()?;
    std::fs::write(
        root.join("packages/runtimed/src/request-types.ts"),
        generated_request_types_ts(),
    )?;
    std::fs::write(
        root.join("packages/runtimed/src/protocol-contract.ts"),
        generated_protocol_contract_ts(),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_typescript_bindings_are_current() -> std::io::Result<()> {
        let root = workspace_root()?;
        let request_types =
            std::fs::read_to_string(root.join("packages/runtimed/src/request-types.ts"))?;
        let protocol_contract =
            std::fs::read_to_string(root.join("packages/runtimed/src/protocol-contract.ts"))?;

        assert_eq!(
            request_types,
            generated_request_types_ts(),
            "packages/runtimed/src/request-types.ts is stale; run `cargo run -p notebook-protocol --bin generate-runtimed-types`"
        );
        assert_eq!(
            protocol_contract,
            generated_protocol_contract_ts(),
            "packages/runtimed/src/protocol-contract.ts is stale; run `cargo run -p notebook-protocol --bin generate-runtimed-types`"
        );
        Ok(())
    }
}
