// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notebook editor preferences.
 */
export type EditorSettings = {
  /**
   * CSS font-family override for code-oriented notebook editor surfaces.
   * Empty string means use the theme default.
   */
  code_font_family: string;
  /**
   * CSS font-family override for Markdown prose and Markdown input.
   * Empty string means use the theme default.
   */
  markdown_font_family: string;
  /**
   * Show line numbers in CodeMirror editor surfaces. Default off.
   */
  line_numbers: boolean;
};
