// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorTheme } from "./ColorTheme";
import type { CondaDefaults } from "./CondaDefaults";
import type { PixiDefaults } from "./PixiDefaults";
import type { PythonEnvType } from "./PythonEnvType";
import type { Runtime } from "./Runtime";
import type { ThemeMode } from "./ThemeMode";
import type { UvDefaults } from "./UvDefaults";

/**
 * Snapshot of all synced settings.
 */
export type SyncedSettings = {
  /**
   * UI theme mode (light/dark/system)
   */
  theme: ThemeMode;
  /**
   * Color theme (classic/cream)
   */
  color_theme: ColorTheme;
  /**
   * Default runtime for new notebooks
   */
  default_runtime: Runtime;
  /**
   * Default Python environment type (uv or conda)
   */
  default_python_env: PythonEnvType;
  /**
   * UV environment defaults
   */
  uv: UvDefaults;
  /**
   * Conda environment defaults
   */
  conda: CondaDefaults;
  /**
   * Pixi environment defaults
   */
  pixi: PixiDefaults;
  /**
   * How long (in seconds) to keep notebook rooms alive after all clients disconnect.
   * This allows you to close and reopen the window without losing your kernel state.
   * Range: 5 seconds to 7 days (604800 seconds).
   */
  keep_alive_secs: bigint;
  /**
   * Whether the user has completed the first-launch onboarding flow.
   * When false, the app shows the onboarding screen on startup.
   */
  onboarding_completed: boolean;
  /**
   * Number of prewarmed UV environments to keep ready. 0 disables the pool.
   */
  uv_pool_size: bigint;
  /**
   * Number of prewarmed Conda environments to keep ready. 0 disables the pool.
   */
  conda_pool_size: bigint;
  /**
   * Number of prewarmed Pixi environments to keep ready. 0 disables the pool.
   */
  pixi_pool_size: bigint;
  /**
   * Install the curated data-science package set in prewarmed pool environments.
   *
   * When true, UV/Conda/Pixi pools include pandas, polars, matplotlib,
   * plotly, and altair in addition to the managed notebook runtime. Project
   * notebooks with explicit dependencies are unaffected.
   */
  install_default_data_packages: boolean;
  /**
   * Disable the nteract kernel launcher and fall back to the legacy
   * `ipykernel_launcher` entry point.
   *
   * The nteract launcher is now the default path so Python kernels can
   * register rich DataFrame and exception formatters before the first user
   * cell. This opt-out flag is an escape hatch for environments that need
   * vanilla IPython launch behavior.
   */
  disable_nteract_launcher: boolean;
  /**
   * Disable comments UI surfaces while keeping comments sync active.
   */
  disable_comments: boolean;
  /**
   * Disable automatic code formatting on cell execution and notebook save.
   */
  disable_auto_format: boolean;
  /**
   * Redact eligible environment variable values from text outputs for newly
   * launched or restarted kernels.
   *
   * The runtime agent applies this before output manifests or blobs are
   * written, so the setting is global-only and intentionally not stored in
   * notebook metadata.
   */
  redact_env_values_in_outputs: boolean;
  /**
   * Merge the daemon's captured shell startup env into each kernel launch's
   * `env_vars`. Combined with `redact_env_values_in_outputs`, the user's
   * shell secrets reach the kernel but stay out of outputs and the blob
   * store. Default `true` to match Jupyter's behavior, but redacted on the
   * way out.
   */
  import_shell_environment: boolean;
  /**
   * Opaque per-install UUIDv4. Generated on first heartbeat, persisted in
   * settings. Not derived from any identifying data.
   */
  install_id: string;
  /**
   * Master telemetry switch. When false, no heartbeat pings are sent.
   */
  telemetry_enabled: boolean;
  /**
   * Whether the user has explicitly recorded a telemetry decision (pressed
   * either the "You can count on me!" or "Opt out of metrics, continue"
   * button during onboarding). Default false. Until this is true, no
   * heartbeat fires, even when `telemetry_enabled = true`. Satisfies the
   * GDPR "clear affirmative action" requirement.
   */
  telemetry_consent_recorded: boolean;
  /**
   * Unix-seconds timestamp of the last successful daemon heartbeat.
   */
  telemetry_last_daemon_ping_at?: bigint | null;
  /**
   * Unix-seconds timestamp of the last successful app heartbeat.
   */
  telemetry_last_app_ping_at?: bigint | null;
  /**
   * Unix-seconds timestamp of the last successful MCP heartbeat.
   */
  telemetry_last_mcp_ping_at?: bigint | null;
};
