[package]
name = "automerge-store"
version = "0.1.1"
edition.workspace = true
description = "Durable, content-addressed storage for Automerge documents"
repository.workspace = true
license.workspace = true

[dependencies]
automerge = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
automerge-legacy = { package = "automerge", git = "https://github.com/nteract/automerge", rev = "3fb6af5cc3af23b79f27cebfa339c8c98987e7b7" }
base64 = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
