// Regenerates the derived inputs design-sync's converter consumes for the
// nteract Elements component library. Run from the repo root (this is
// cfg.buildCmd). Deterministic: safe to re-run on every sync.
//
//   1. entry.tsx        barrel re-exporting the synced components
//   2. compiled.css     Tailwind v4 compiled from .design-sync/css-entry.css
//   3. types/*.d.ts     real declaration emit via tsc (the API contract)
//   4. types/index.d.ts barrel over the emitted declarations
//
// Everything it writes is gitignored — this script + package.json are the
// only committed pieces of the synth package.
import { execFileSync } from "node:child_process";
import { readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // .design-sync/synthpkg
const repo = resolve(here, "..", ".."); // repo root

// Source groups fed to the converter. `ui` is the whole shadcn primitive dir;
// `cell` is a CURATED set of the notebook cell primitives that render from
// plain props (editor/output/notebook-doc-heavy cells are deliberately left
// out — they need providers/fixtures we don't wire here). Keeping cell curated
// (not glob-all) also keeps the bundle from pulling CodeMirror/plotly/widget
// deps in through the heavy cells.
const groups = [
  {
    dir: "ui",
    mods: readdirSync(join(repo, "src", "components", "ui"))
      .filter((f) => f.endsWith(".tsx") && !/\.(test|spec|stories)\.tsx$/.test(f))
      .map((f) => f.replace(/\.tsx$/, ""))
      .sort(),
  },
  {
    dir: "cell",
    mods: [
      "CellContainer",
      "CellInsertionRibbon",
      "CellPresenceIndicators",
      "CellSkeleton",
      "CodeCellCurrentLine",
      "CompactExecutionButton",
      "ExecutionCount",
    ],
  },
  {
    // Owned output renderers — we control the React (not mime→passthrough).
    // html-output is EXCLUDED: it throws unless inside a sandboxed iframe, so it
    // can't render in a static card. Skipped by owner: plotly, vega, image, pdf,
    // audio, video, geojson (mime passthroughs). markdown/traceback pull
    // @codemirror/lang-* + @lezer for static highlighting — synchronous, bundles fine.
    // math-output is DEFERRED: it does `import "katex/dist/katex.min.css"`, and the
    // converter's bundle has no .ttf loader for the fonts katex's CSS references
    // (bundle.mjs loads .woff/.woff2 only). Fixing it means either a declared
    // .ttf-dataurl bundle override or shipping katex CSS via css-entry — a small
    // follow-up, not a fork of the bundle contract here.
    dir: "outputs",
    mods: ["ansi-output", "json-output", "traceback-output"],
  },
  {
    // Comment affordances — prop-driven pieces of the commenting UI.
    // NotebookCommentsPanel is DEFERRED with the katex pass: it renders quotes
    // via ProjectedMarkdownView, which imports katex CSS (the same .ttf loader
    // wall that defers math-output above). It is otherwise fully prop-driven
    // (projection + callbacks) and joins this group when katex fonts ship.
    dir: "comments",
    mods: ["CommentSelectionAffordance", "CommentMarkIcon"],
  },
];

// 1. barrel entry (the bundle's import graph = exactly these modules)
const importLines = groups.flatMap((g) =>
  g.mods.map((m) => `export * from "../../src/components/${g.dir}/${m}";`),
);
writeFileSync(
  join(here, "entry.tsx"),
  `// GENERATED by build.mjs — do not edit.\n${importLines.join("\n")}\n`,
);
const total = groups.reduce((n, g) => n + g.mods.length, 0);
console.error(
  `entry.tsx: ${total} modules (${groups.map((g) => `${g.dir}:${g.mods.length}`).join(", ")})`,
);

// 2. Tailwind compile
execFileSync(
  join(repo, ".ds-sync", "node_modules", ".bin", "tailwindcss"),
  ["-i", join(repo, ".design-sync", "css-entry.css"), "-o", join(here, "compiled.css")],
  { stdio: "inherit" },
);
console.error("compiled.css written");

// 3. declaration emit — real .d.ts is the design agent's API contract
const typesDir = join(here, "types");
rmSync(typesDir, { recursive: true, force: true });
mkdirSync(typesDir, { recursive: true });
const tsconfig = join(here, "tsconfig.emit.json");
writeFileSync(
  tsconfig,
  JSON.stringify(
    {
      compilerOptions: {
        declaration: true,
        emitDeclarationOnly: true,
        outDir: "./types",
        // rootDir spans all of src/ so imported-but-outside files (@/lib/utils,
        // @/hooks/useTheme) emit UNDER types/ instead of polluting the source tree.
        rootDir: "../../src",
        jsx: "react-jsx",
        module: "esnext",
        moduleResolution: "bundler",
        target: "es2020",
        skipLibCheck: true,
        strict: false,
        noEmitOnError: false,
        esModuleInterop: true,
        baseUrl: "../..",
        paths: { "@/*": ["src/*"] },
      },
      // ui as a dir; cell scoped to the curated files so tsc doesn't type-check the
      // heavy deferred cells (and their editor/plotly type graphs).
      include: [
        "../../src/components/ui/**/*.tsx",
        ...groups
          .filter((g) => g.dir !== "ui")
          .flatMap((g) => g.mods.map((m) => `../../src/components/${g.dir}/${m}.tsx`)),
      ],
      exclude: ["../../src/components/**/*.{test,spec,stories}.tsx"],
    },
    null,
    2,
  ),
);

const tsc = join(repo, "node_modules", ".bin", "tsc");
try {
  execFileSync(tsc, ["-p", tsconfig], { stdio: "inherit" });
} catch {
  // tsc exits non-zero on type errors but still emits declarations — keep going.
  console.error("tsc reported diagnostics (declarations still emitted where possible)");
}

// 4. types barrel — generated from the curated module lists (not a glob of the
// emitted tree, so imported-but-unsynced files that also emit under types/
// don't leak into the export set). rootDir=src → types/components/<dir>/<name>.d.ts
const missing = [];
const barrelLines = groups.flatMap((g) =>
  g.mods
    .map((m) => {
      if (!existsSync(join(typesDir, "components", g.dir, `${m}.d.ts`))) {
        missing.push(`${g.dir}/${m}`);
        return null;
      }
      return `export * from "./components/${g.dir}/${m}";`;
    })
    .filter(Boolean),
);
writeFileSync(
  join(typesDir, "index.d.ts"),
  `// GENERATED by build.mjs — do not edit.\n${barrelLines.join("\n")}\n`,
);
console.error(`types/: ${barrelLines.length} declarations barrelled`);
if (missing.length)
  console.error(`WARNING: no .d.ts emitted for ${missing.join(", ")} — props degrade to synth`);
