// Regenerates the derived inputs design-sync's converter consumes for the
// nteract Elements component library. Run from the repo root (this is
// cfg.buildCmd). Deterministic: safe to re-run on every sync.
//
//   1. entry.tsx        barrel re-exporting every src/components/ui component
//   2. compiled.css     Tailwind v4 compiled from .design-sync/css-entry.css
//   3. types/*.d.ts     real declaration emit via tsc (the API contract)
//   4. types/index.d.ts barrel over the emitted declarations
//
// Everything it writes is gitignored — this script + package.json are the
// only committed pieces of the synth package.
import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));   // .design-sync/synthpkg
const repo = resolve(here, '..', '..');                 // repo root
const uiDir = join(repo, 'src', 'components', 'ui');

// 1. component modules → barrel entry
const mods = readdirSync(uiDir)
  .filter((f) => /\.tsx$/.test(f) && !/\.(test|spec|stories)\.tsx$/.test(f))
  .map((f) => f.replace(/\.tsx$/, ''))
  .sort();
if (!mods.length) { console.error('no ui components found'); process.exit(1); }

writeFileSync(
  join(here, 'entry.tsx'),
  `// GENERATED by build.mjs — do not edit.\n` +
    mods.map((m) => `export * from "../../src/components/ui/${m}";`).join('\n') + '\n',
);
console.error(`entry.tsx: ${mods.length} modules`);

// 2. Tailwind compile
execFileSync(
  join(repo, '.ds-sync', 'node_modules', '.bin', 'tailwindcss'),
  ['-i', join(repo, '.design-sync', 'css-entry.css'), '-o', join(here, 'compiled.css')],
  { stdio: 'inherit' },
);
console.error('compiled.css written');

// 3. declaration emit
const typesDir = join(here, 'types');
rmSync(typesDir, { recursive: true, force: true });
mkdirSync(typesDir, { recursive: true });
const tsconfig = join(here, 'tsconfig.emit.json');
writeFileSync(tsconfig, JSON.stringify({
  compilerOptions: {
    declaration: true,
    emitDeclarationOnly: true,
    outDir: './types',
    // rootDir spans all of src/ so imported-but-outside files (@/lib/utils,
    // @/hooks/useTheme) emit UNDER types/ instead of polluting the source tree.
    rootDir: '../../src',
    jsx: 'react-jsx',
    module: 'esnext',
    moduleResolution: 'bundler',
    target: 'es2020',
    skipLibCheck: true,
    strict: false,
    noEmitOnError: false,
    esModuleInterop: true,
    baseUrl: '../..',
    paths: { '@/*': ['src/*'] },
  },
  include: ['../../src/components/ui/**/*.tsx'],
  exclude: ['../../src/components/ui/**/*.{test,spec,stories}.tsx'],
}, null, 2));

const tsc = join(repo, 'node_modules', '.bin', 'tsc');
try {
  execFileSync(tsc, ['-p', tsconfig], { stdio: 'inherit' });
} catch {
  // tsc exits non-zero on type errors but still emits declarations — keep going.
  console.error('tsc reported diagnostics (declarations still emitted where possible)');
}

// 4. types barrel over what actually emitted (rootDir=src → types/components/ui/<name>.d.ts)
const uiTypesDir = join(typesDir, 'components', 'ui');
const emitted = existsSync(uiTypesDir)
  ? readdirSync(uiTypesDir).filter((f) => /\.d\.ts$/.test(f)).map((f) => f.replace(/\.d\.ts$/, '')).sort()
  : [];
writeFileSync(
  join(typesDir, 'index.d.ts'),
  `// GENERATED by build.mjs — do not edit.\n` +
    emitted.map((m) => `export * from "./components/ui/${m}";`).join('\n') + '\n',
);
console.error(`types/: ${emitted.length} declarations emitted`);
if (emitted.length < mods.length)
  console.error(`WARNING: ${mods.length - emitted.length} module(s) produced no .d.ts — props for those degrade to synth`);
