import { expect, test, type Page } from "@playwright/test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { writeFile } from "node:fs/promises";

interface NotebookFixture {
  name: string;
  path: string;
  cellCount: number;
  bytes: number;
  external: boolean;
}

interface LoadBenchEvent {
  name: string;
  t: number;
  detail?: {
    count?: number;
  };
}

interface LoadBenchResult {
  fixture: NotebookFixture;
  events: LoadBenchEvent[];
  timings: {
    toolbarVisibleMs: number | null;
    firstCellAttachedMs: number | null;
    allCellsAttachedMs: number | null;
    notebookSyncedMs: number | null;
    sessionReadyMs: number | null;
  };
  cellTimeline: Array<{ t: number; count: number | null }>;
}

const REAL_NOTEBOOK_NAMES = ["MatplotlibExample.ipynb", "_PreProcess.ipynb"];

function generatedRichOutputNotebook() {
  const pngPayload =
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lqYJiwAAAABJRU5ErkJggg==";
  const cells = [
    {
      cell_type: "markdown",
      metadata: {},
      source: ["# OG ipynb load performance fixture\n", "\n", "Generated by the browser E2E test."],
    },
  ];

  for (let index = 0; index < 12; index += 1) {
    cells.push({
      cell_type: "code",
      execution_count: index + 1,
      metadata: {},
      source: [`print("fixture ${index}")`],
      outputs: [
        {
          output_type: "stream",
          name: "stdout",
          text: [`fixture ${index}\n`],
        },
        {
          output_type: "display_data",
          data: {
            "text/plain": [`generated display ${index}`],
            "image/png": pngPayload,
          },
          metadata: {},
        },
      ],
    });
  }

  return {
    cells,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3",
      },
      language_info: {
        name: "python",
        pycodemirror_mode: { name: "ipython", version: 3 },
      },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
}

function notebookCellCount(notebookPath: string): number {
  const notebook = JSON.parse(fs.readFileSync(notebookPath, "utf8"));
  return Array.isArray(notebook.cells) ? notebook.cells.length : 0;
}

function createGeneratedFixture(dir: string): NotebookFixture {
  const notebookPath = path.join(dir, "generated-rich-output.ipynb");
  fs.writeFileSync(notebookPath, JSON.stringify(generatedRichOutputNotebook(), null, 2));
  return {
    name: path.basename(notebookPath),
    path: notebookPath,
    cellCount: notebookCellCount(notebookPath),
    bytes: fs.statSync(notebookPath).size,
    external: false,
  };
}

function optionalExternalFixtures(): NotebookFixture[] {
  const sourceDir = process.env.NTERACT_OG_IPYNB_LOAD_FIXTURE_DIR;
  if (!sourceDir) return [];

  return REAL_NOTEBOOK_NAMES.flatMap((name) => {
    const notebookPath = path.join(sourceDir, name);
    if (!fs.existsSync(notebookPath)) return [];
    return [
      {
        name,
        path: notebookPath,
        cellCount: notebookCellCount(notebookPath),
        bytes: fs.statSync(notebookPath).size,
        external: true,
      },
    ];
  });
}

async function installLoadBenchProbe(page: Page, expectedCellCount: number) {
  await page.addInitScript((count) => {
    type BenchEvent = { name: string; t: number; detail?: Record<string, unknown> };
    const state = {
      events: [] as BenchEvent[],
      seen: new Set<string>(),
      lastCellCount: -1,
      record(name: string, detail: Record<string, unknown> = {}) {
        this.events.push({ name, t: performance.now(), detail });
      },
      markOnce(name: string, detail: Record<string, unknown> = {}) {
        if (this.seen.has(name)) return;
        this.seen.add(name);
        this.record(name, detail);
      },
    };

    (
      window as unknown as {
        __nteractOgIpynbLoadBench?: typeof state;
      }
    ).__nteractOgIpynbLoadBench = state;

    const visible = (element: Element | null) =>
      Boolean(
        element &&
        ((element as HTMLElement).offsetWidth ||
          (element as HTMLElement).offsetHeight ||
          element.getClientRects().length),
      );

    const sample = () => {
      if (visible(document.querySelector('[data-testid="notebook-toolbar"]'))) {
        state.markOnce("toolbar-visible");
      }

      const cells = document.querySelectorAll("[data-cell-type]");
      if (cells.length !== state.lastCellCount) {
        state.lastCellCount = cells.length;
        state.record("cell-count", { count: cells.length });
      }
      if (cells.length > 0) {
        state.markOnce("first-cell-attached", { count: cells.length });
      }
      if (cells.length >= count) {
        state.markOnce("all-cells-attached", { count: cells.length });
      }

      if (
        document.querySelector("[data-notebook-synced]")?.getAttribute("data-notebook-synced") ===
        "true"
      ) {
        state.markOnce("notebook-synced");
      }

      if (
        document.querySelector("[data-session-ready]")?.getAttribute("data-session-ready") ===
        "true"
      ) {
        state.markOnce("session-ready");
      }
    };

    const start = () => {
      new MutationObserver(sample).observe(document.documentElement, {
        attributes: true,
        childList: true,
        subtree: true,
      });
      window.setInterval(sample, 50);
      sample();
    };

    if (document.documentElement) {
      start();
    } else {
      document.addEventListener("DOMContentLoaded", start, { once: true });
    }
  }, expectedCellCount);
}

async function waitForNotebookLoad(page: Page, expectedCellCount: number) {
  await expect(page.getByTestId("notebook-toolbar")).toBeVisible({ timeout: 30_000 });
  await expect
    .poll(() => page.locator("[data-cell-type]").count(), { timeout: 60_000 })
    .toBeGreaterThan(0);
  await expect(page.locator("[data-cell-type]")).toHaveCount(expectedCellCount, {
    timeout: 60_000,
  });
  await expect(page.locator("[data-notebook-synced]")).toHaveAttribute(
    "data-notebook-synced",
    "true",
    { timeout: 60_000 },
  );
}

function firstEventTime(events: LoadBenchEvent[], name: string) {
  const event = events.find((candidate) => candidate.name === name);
  return typeof event?.t === "number" ? event.t : null;
}

function cellTimeline(events: LoadBenchEvent[]) {
  return events
    .filter((event) => event.name === "cell-count")
    .map((event) => ({
      t: event.t,
      count: typeof event.detail?.count === "number" ? event.detail.count : null,
    }));
}

function assertMonotonicCellTimeline(timeline: Array<{ count: number | null }>) {
  let last = -1;
  for (const sample of timeline) {
    if (sample.count == null) continue;
    expect(sample.count).toBeGreaterThanOrEqual(last);
    last = sample.count;
  }
}

async function measureFixture(page: Page, fixture: NotebookFixture): Promise<LoadBenchResult> {
  await installLoadBenchProbe(page, fixture.cellCount);
  await page.goto(`/?path=${encodeURIComponent(fixture.path)}&environment_mode=notebook`, {
    waitUntil: "domcontentloaded",
  });
  await waitForNotebookLoad(page, fixture.cellCount);

  const events = await page.evaluate(
    () =>
      (
        window as unknown as {
          __nteractOgIpynbLoadBench?: { events: LoadBenchEvent[] };
        }
      ).__nteractOgIpynbLoadBench?.events ?? [],
  );

  return {
    fixture,
    events,
    timings: {
      toolbarVisibleMs: firstEventTime(events, "toolbar-visible"),
      firstCellAttachedMs: firstEventTime(events, "first-cell-attached"),
      allCellsAttachedMs: firstEventTime(events, "all-cells-attached"),
      notebookSyncedMs: firstEventTime(events, "notebook-synced"),
      sessionReadyMs: firstEventTime(events, "session-ready"),
    },
    cellTimeline: cellTimeline(events),
  };
}

test.describe("OG ipynb load performance smoke", () => {
  test("attaches cells before synced state and records load milestones", async ({
    page,
  }, testInfo) => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nteract-og-ipynb-load-"));
    try {
      const fixtures = [createGeneratedFixture(dir), ...optionalExternalFixtures()];
      const results: LoadBenchResult[] = [];

      for (const fixture of fixtures) {
        const fixturePage = await page.context().newPage();
        try {
          results.push(await measureFixture(fixturePage, fixture));
        } finally {
          await fixturePage.close();
        }
      }

      for (const result of results) {
        expect(result.fixture.cellCount).toBeGreaterThan(0);
        expect(result.timings.firstCellAttachedMs).not.toBeNull();
        expect(result.timings.allCellsAttachedMs).not.toBeNull();
        expect(result.timings.notebookSyncedMs).not.toBeNull();
        expect(result.timings.firstCellAttachedMs!).toBeLessThan(result.timings.notebookSyncedMs!);
        expect(result.cellTimeline.at(-1)?.count).toBe(result.fixture.cellCount);
        assertMonotonicCellTimeline(result.cellTimeline);
      }

      const artifactPath = testInfo.outputPath("og-ipynb-load-performance.json");
      await writeFile(artifactPath, JSON.stringify({ results }, null, 2));
      await testInfo.attach("og-ipynb-load-performance.json", {
        path: artifactPath,
        contentType: "application/json",
      });
      console.info(`[og-ipynb-load-performance]\n${JSON.stringify(results, null, 2)}`);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
