/**
 * Fixture-based integration tests — real daemon-authored Automerge documents
 * loaded into WASM handles, synced through DirectTransport + SyncEngine.
 *
 * These fixtures are generated by `cargo test -p notebook-doc --test generate_fixtures`
 * and contain daemon-only mutations (outputs, execution counts) that can't be
 * done with WASM handles alone.
 *
 * Outputs mirror production exactly: inline manifest objects in RuntimeStateDoc's
 * execution output map, each keyed by a stable `output_id` (UUIDv5-derived for
 * reproducibility). The WASM handle exposes them via `get_cell_outputs(cell_id)`
 * as an array of narrowed manifests.
 *
 * The flow:
 * 1. Rust generates a NotebookDoc + RuntimeStateDoc with daemon mutations.
 * 2. This test loads `doc.bin` + `state_doc.bin` into a WASM server handle.
 * 3. A fresh WASM client syncs via DirectTransport (real 2-party Automerge sync).
 * 4. Assertions verify the manifest shape surfaced to the UI.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { VirtualAction, VirtualTimeScheduler } from "rxjs";
import { describe, expect, it } from "vite-plus/test";
import { DirectTransport, type ServerHandle } from "../src/direct-transport";
import type { ExecutionViewChangeset, SyncableHandle } from "../src/handle";
import { SyncEngine } from "../src/sync-engine";
import { initWasm, type NotebookHandle } from "./wasm-harness";

// ── Fixture loading ──────────────────────────────────────────────────

const FIXTURES_DIR = resolve(__dirname, "fixtures");

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const ARROW_STREAM_MANIFEST_MIME = "application/vnd.nteract.arrow-stream-manifest+json";

interface ScenarioManifest {
  scenario: string;
  description: string;
  expected?: Record<string, unknown>;
  [key: string]: unknown;
}

interface ManifestOutput {
  output_type: "stream" | "error" | "display_data" | "execute_result";
  output_id: string;
  name?: string;
  text?: unknown;
  ename?: string;
  evalue?: string;
  traceback?: unknown;
  data?: Record<string, unknown>;
  execution_count?: number;
}

function loadManifest(scenario: string): ScenarioManifest {
  const path = resolve(FIXTURES_DIR, scenario, "manifest.json");
  return JSON.parse(readFileSync(path, "utf-8"));
}

function loadDocBytes(scenario: string): Uint8Array {
  const path = resolve(FIXTURES_DIR, scenario, "doc.bin");
  return new Uint8Array(readFileSync(path));
}

function loadStateDocBytes(scenario: string): Uint8Array | null {
  const path = resolve(FIXTURES_DIR, scenario, "state_doc.bin");
  if (!existsSync(path)) return null;
  return new Uint8Array(readFileSync(path));
}

/** Resolve a ContentRef to its inline string, throwing on blob refs. */
function resolveInline(contentRef: unknown): string {
  const r = contentRef as Record<string, unknown>;
  if ("inline" in r) return r.inline as string;
  throw new Error(`Expected inline ContentRef, got: ${JSON.stringify(contentRef)}`);
}

function cellOutputs(handle: NotebookHandle, cellId: string): ManifestOutput[] {
  const raw = handle.get_cell_outputs(cellId);
  if (!raw) return [];
  return raw as ManifestOutput[];
}

// ── WASM server handle adapter ──────────────────────────────────────

class WasmServerHandle implements ServerHandle {
  readonly handle: NotebookHandle;

  constructor(handle: NotebookHandle) {
    this.handle = handle;
  }

  flush_local_changes(): Uint8Array | null {
    return this.handle.flush_local_changes() ?? null;
  }

  receive_sync_message(message: Uint8Array): boolean {
    return this.handle.receive_sync_message(message);
  }

  reset_sync_state(): void {
    this.handle.reset_sync_state();
  }
}

// ── Test setup ──────────────────────────────────────────────────────

async function setupFixtureSync(scenario: string) {
  const Handle = await initWasm();
  const docBytes = loadDocBytes(scenario);
  const stateDocBytes = loadStateDocBytes(scenario);

  // Load the daemon-authored doc into a WASM server handle
  const server = Handle.load(docBytes);
  if (stateDocBytes) {
    server.load_state_doc(stateDocBytes);
  }
  const serverAdapter = new WasmServerHandle(server);

  // Fresh client — knows nothing, will learn via sync
  const client = Handle.create_bootstrap(`fixture-client-${Date.now()}`);
  if (stateDocBytes) {
    // Client also needs the state doc to read outputs via get_cell_outputs
    client.load_state_doc(stateDocBytes);
  }

  const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
  const transport = new DirectTransport(serverAdapter);
  const engine = new SyncEngine({
    getHandle: () => client as unknown as SyncableHandle,
    transport,
    presenceHeartbeat: {
      intervalMs: 15_000,
      encode: () => new Uint8Array([0]),
    },
    scheduler,
  });

  async function startAndCompleteSync(): Promise<void> {
    engine.start();

    const syncComplete = new Promise<void>((resolve) => {
      const sub = engine.initialSyncComplete$.subscribe(() => {
        sub.unsubscribe();
        resolve();
      });
    });

    transport.pushSessionStatus({
      notebook_doc: "pending",
      runtime_state: "pending",
      initial_load: { phase: "not_needed" },
    });

    // Kick off the handshake
    engine.flush();
    transport.pushSessionStatus({
      notebook_doc: "syncing",
      runtime_state: "syncing",
      initial_load: { phase: "not_needed" },
    });

    // Run sync rounds until convergence
    for (let i = 0; i < 20; i++) {
      const pushed = transport.pushServerChanges();
      if (!pushed) break;
      await Promise.resolve();
    }

    transport.pushSessionStatus({
      notebook_doc: "interactive",
      runtime_state: "ready",
      initial_load: { phase: "not_needed" },
    });

    await syncComplete;
  }

  return {
    server,
    client,
    engine,
    transport,
    scheduler,
    startAndCompleteSync,
    dispose() {
      engine.stop();
      server.free();
      client.free();
    },
  };
}

// ── Tests ────────────────────────────────────────────────────────────

describe("fixture-based integration: daemon-authored docs through WASM sync", () => {
  describe("output_streaming", () => {
    it("client receives inline stream manifests with stable output_ids", async () => {
      const manifest = loadManifest("output_streaming");
      const h = await setupFixtureSync("output_streaming");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe(manifest.expected!.source as string);
      expect(h.client.get_cell_execution_count("cell-1")).toBe(
        manifest.expected!.execution_count as string,
      );

      const outputs = cellOutputs(h.client, "cell-1");
      expect(outputs).toHaveLength(manifest.expected!.output_count as number);

      const expectedIds = manifest.expected!.output_ids as string[];
      const expectedTexts = manifest.expected!.output_texts as string[];
      for (let i = 0; i < outputs.length; i++) {
        const o = outputs[i];
        expect(o.output_type).toBe("stream");
        expect(o.output_id).toBe(expectedIds[i]);
        expect(o.output_id).toMatch(UUID_RE);
        expect(o.name).toBe("stdout");
        expect(resolveInline(o.text)).toBe(expectedTexts[i]);
      }

      h.dispose();
    });
  });

  describe("execution_with_error", () => {
    it("client receives the error manifest after sync", async () => {
      const manifest = loadManifest("execution_with_error");
      const h = await setupFixtureSync("execution_with_error");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe("1 / 0");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = cellOutputs(h.client, "cell-1");
      expect(outputs).toHaveLength(1);

      const [err] = outputs;
      const expectedIds = manifest.expected!.output_ids as string[];
      expect(err.output_id).toBe(expectedIds[0]);
      expect(err.output_type).toBe("error");
      expect(err.ename).toBe("ZeroDivisionError");
      expect(err.evalue).toBe("division by zero");

      const traceback = JSON.parse(resolveInline(err.traceback));
      expect(traceback).toHaveLength(2);
      expect(traceback[1]).toContain("ZeroDivisionError");

      h.dispose();
    });
  });

  describe("re_execution", () => {
    it("client sees only the second execution's output after sync", async () => {
      const manifest = loadManifest("re_execution");
      const h = await setupFixtureSync("re_execution");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("2");

      const outputs = cellOutputs(h.client, "cell-1");
      expect(outputs).toHaveLength(1);

      const [result] = outputs;
      const expectedIds = manifest.expected!.output_ids as string[];
      expect(result.output_id).toBe(expectedIds[0]);
      expect(result.output_type).toBe("execute_result");
      expect(result.execution_count).toBe(2);

      const data = result.data as Record<string, unknown>;
      expect(resolveInline(data["text/plain"])).toBe("42");

      h.dispose();
    });
  });

  describe("multi_cell_execution", () => {
    it("client receives all cells with correct execution state", async () => {
      const manifest = loadManifest("multi_cell_execution");
      const h = await setupFixtureSync("multi_cell_execution");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(3);

      // cell-1: code, executed, no outputs
      expect(h.client.get_cell_type("cell-1")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");
      expect(cellOutputs(h.client, "cell-1")).toHaveLength(0);

      // cell-2: code, executed, one stream output
      expect(h.client.get_cell_type("cell-2")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-2")).toBe("2");
      const cell2Outputs = cellOutputs(h.client, "cell-2");
      expect(cell2Outputs).toHaveLength(1);

      const cells = manifest.expected!.cells as Array<Record<string, unknown>>;
      const cell2Expected = cells.find((c) => c.cell_id === "cell-2")!;
      const expectedIds = cell2Expected.output_ids as string[];
      expect(cell2Outputs[0].output_id).toBe(expectedIds[0]);
      expect(cell2Outputs[0].output_type).toBe("stream");
      expect(resolveInline(cell2Outputs[0].text)).toBe("42\n");

      // cell-3: markdown, no execution
      expect(h.client.get_cell_type("cell-3")).toBe("markdown");
      expect(h.client.get_cell_source("cell-3")).toBe("# Results");

      h.dispose();
    });

    it("projects execution-view changesets from real WASM fixture docs", async () => {
      const Handle = await initWasm();
      const client = Handle.load(loadDocBytes("multi_cell_execution"));
      client.load_state_doc(loadStateDocBytes("multi_cell_execution")!);

      const changeset = (
        client as unknown as {
          project_execution_view_changeset(): ExecutionViewChangeset;
        }
      ).project_execution_view_changeset();

      const cell1ExecutionId = client.get_cell_execution_id("cell-1");
      const cell2ExecutionId = client.get_cell_execution_id("cell-2");
      expect(cell1ExecutionId).toBe("exec-001");
      expect(cell2ExecutionId).toBe("exec-002");

      const pointerChanges = changeset.cell_pointer_changes ?? [];
      expect(pointerChanges).toContainEqual(["cell-1", cell1ExecutionId]);
      expect(pointerChanges).toContainEqual(["cell-2", cell2ExecutionId]);

      const upserts = new Map(changeset.execution_upserts ?? []);
      expect(upserts.get(cell1ExecutionId!)).toEqual({
        execution_count: null,
        status: "done",
        success: true,
        output_ids: [],
      });
      expect(upserts.get(cell2ExecutionId!)).toEqual({
        execution_count: null,
        status: "done",
        success: true,
        output_ids: ["8f359d50-e5a4-5243-a71a-120209c0adb1"],
      });

      expect(changeset.queue).toEqual({
        executing_execution_id: null,
        queued_execution_ids: [],
        notebook: {
          executing_cell_id: null,
          queued_cell_ids: [],
        },
      });

      client.free();
    });
  });

  describe("display_data_output", () => {
    it("client receives a display_data manifest with mixed content refs", async () => {
      const manifest = loadManifest("display_data_output");
      const h = await setupFixtureSync("display_data_output");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = cellOutputs(h.client, "cell-1");
      expect(outputs).toHaveLength(1);

      const [display] = outputs;
      const expectedIds = manifest.expected!.output_ids as string[];
      expect(display.output_id).toBe(expectedIds[0]);
      expect(display.output_type).toBe("display_data");

      const data = display.data as Record<string, unknown>;
      // text/plain is inlined
      expect(resolveInline(data["text/plain"])).toBe("<Figure size 640x480>");

      // image/png has a blob ContentRef. No blob_port is set on the client
      // handle in this test, so WASM's `resolve_content_ref` keeps binary
      // blob refs as `{blob, size}` — that is the exact shape that should
      // reach the UI here. A regression to `{inline}` or `{url}` would mean
      // binary MIME handling changed silently.
      const image = data["image/png"] as Record<string, unknown>;
      expect(image.blob).toBe("fake_image_blob_hash_for_fixture_testing_only_not_real");
      expect(image.size).toBe(12345);
      expect("inline" in image).toBe(false);
      expect("url" in image).toBe(false);

      h.dispose();
    });
  });

  describe("sift_arrow_output", () => {
    it("client receives a Sift-compatible Arrow manifest with blob chunks", async () => {
      const manifest = loadManifest("sift_arrow_output");
      const h = await setupFixtureSync("sift_arrow_output");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = cellOutputs(h.client, "cell-1");
      expect(outputs).toHaveLength(1);

      const [result] = outputs;
      const expected = manifest.expected!;
      const expectedIds = expected.output_ids as string[];
      expect(result.output_id).toBe(expectedIds[0]);
      expect(result.output_type).toBe("execute_result");
      expect(result.execution_count).toBe(1);

      const data = result.data as Record<string, unknown>;
      const arrowManifest = JSON.parse(resolveInline(data[ARROW_STREAM_MANIFEST_MIME])) as {
        chunks: Array<Record<string, unknown>>;
        complete: boolean;
      };
      expect(arrowManifest.complete).toBe(true);
      expect(arrowManifest.chunks).toHaveLength(1);
      expect(arrowManifest.chunks[0].hash).toBe(expected.blob_hash);
      expect(arrowManifest.chunks[0].size).toBe(expected.blob_size);
      expect(resolveInline(data["text/plain"])).toContain("shape:");

      h.dispose();
    });
  });

  describe("changeset emission from daemon-authored docs", () => {
    it("emits changesets when incremental daemon changes arrive", async () => {
      const Handle = await initWasm();
      const docBytes = loadDocBytes("output_streaming");

      const server = Handle.load(docBytes);
      const serverAdapter = new WasmServerHandle(server);

      const client = Handle.create_bootstrap(`fixture-changeset-${Date.now()}`);
      const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
      const transport = new DirectTransport(serverAdapter);
      const engine = new SyncEngine({
        getHandle: () => client as unknown as SyncableHandle,
        transport,
        presenceHeartbeat: {
          intervalMs: 15_000,
          encode: () => new Uint8Array([0]),
        },
        scheduler,
      });

      // Start and complete initial sync
      engine.start();
      const syncComplete = new Promise<void>((resolve) => {
        const sub = engine.initialSyncComplete$.subscribe(() => {
          sub.unsubscribe();
          resolve();
        });
      });
      transport.pushSessionStatus({
        notebook_doc: "pending",
        runtime_state: "pending",
        initial_load: { phase: "not_needed" },
      });
      engine.flush();
      transport.pushSessionStatus({
        notebook_doc: "syncing",
        runtime_state: "syncing",
        initial_load: { phase: "not_needed" },
      });
      for (let i = 0; i < 20; i++) {
        if (!transport.pushServerChanges()) break;
        await Promise.resolve();
      }
      transport.pushSessionStatus({
        notebook_doc: "interactive",
        runtime_state: "ready",
        initial_load: { phase: "not_needed" },
      });
      await syncComplete;

      // Subscribe to changesets and make an incremental server change
      const changesets: unknown[] = [];
      const sub = engine.cellChanges$.subscribe((cs) => changesets.push(cs));

      server.update_source("cell-1", "print('changed')");
      transport.pushServerChanges();

      // Advance past coalescing window
      const target = scheduler.frame + 50;
      scheduler.maxFrames = target;
      scheduler.schedule(() => {}, 50);
      scheduler.flush();

      expect(changesets.length).toBeGreaterThan(0);

      sub.unsubscribe();
      engine.stop();
      server.free();
      client.free();
    });
  });
});
