// Generated by scripts/build-execution-store.mjs. Do not edit.
export interface ExecutionViewSnapshot {
    execution_count: number | null;
    status: "queued" | "running" | "done" | "error" | "cancelled" | (string & {});
    success: boolean | null;
    output_ids: string[];
    submitted_by_actor_label?: string | null;
}
export interface ExecutionQueueProjection {
    executing_execution_id?: string | null;
    queued_execution_ids: string[];
    notebook?: {
        executing_cell_id?: string | null;
        queued_cell_ids: string[];
    } | null;
}
export interface ExecutionViewChangeset {
    cell_pointer_changes?: Array<[cell_id: string, execution_id: string | null]>;
    execution_upserts?: Array<[execution_id: string, snapshot: ExecutionViewSnapshot]>;
    removed_execution_ids?: string[];
    queue?: ExecutionQueueProjection | null;
}
/** Immutable consumer snapshots; wire payload types above remain mutable. */
export type ExecutionSnapshot = Readonly<Omit<ExecutionViewSnapshot, "output_ids">> & {
    readonly output_ids: readonly string[];
};
export interface NotebookQueueProjectionSnapshot {
    readonly executing_cell_id: string | null;
    readonly queued_cell_ids: readonly string[];
}
export interface ExecutionQueueSnapshot {
    readonly executing_execution_id: string | null;
    readonly queued_execution_ids: readonly string[];
    readonly notebook?: NotebookQueueProjectionSnapshot | null;
}
export interface ExecutionView {
    readonly cell_execution_ids: Readonly<Record<string, string>>;
    readonly executions: Readonly<Record<string, ExecutionSnapshot>>;
    readonly queue: ExecutionQueueSnapshot | null;
}
/** Independent synchronous notebook state. Construction performs no I/O. */
export declare function createNotebookExecutionStore(): {
    subscribeNotebookQueueProjection: (callback: () => void) => () => void;
    getNotebookQueueProjection: () => NotebookQueueProjectionSnapshot;
    setExecution: (execution_id: string, snap: ExecutionSnapshot) => void;
    markExecutionsRuntimeOwned: (execution_ids: Iterable<string>) => void;
    isExecutionRuntimeOwned: (execution_id: string) => boolean;
    setCellExecutionPointer: (cell_id: string, execution_id: string | null) => void;
    setNotebookQueueProjection: (projection: NotebookQueueProjectionSnapshot) => void;
    deleteExecutions: (execution_ids: Iterable<string>) => void;
    getExecutionById: (execution_id: string) => ExecutionSnapshot | undefined;
    getCellExecutionId: (cell_id: string) => string | null;
    getCellIdForExecutionId: (execution_id: string) => string | null;
    resetNotebookExecutions: () => void;
    subscribeExecutionById: (execution_id: string) => (cb: () => void) => () => void;
    getExecutionSnapshotGetter: (execution_id: string) => () => ExecutionSnapshot | undefined;
    subscribeCellExecutionPointer: (cell_id: string) => (cb: () => void) => () => void;
    getCellExecutionIdGetter: (cell_id: string) => () => string | null;
    subscribeExecutionStructureVersion: (callback: () => void) => () => void;
    getExecutionStructureVersionSnapshot: () => number;
    getSnapshot: () => ExecutionView;
    applyChangeset: (changeset: ExecutionViewChangeset | null | undefined, options?: {
        onExecutionSnapshot?: (id: string, snapshot: ExecutionSnapshot) => void;
    }) => void;
};
export type NotebookExecutionStore = ReturnType<typeof createNotebookExecutionStore>;
