// @generated by cargo run -p notebook-protocol --bin generate-runtimed-types
// Do not edit by hand.

import type {
  InitialLoadPhase,
  NotebookDocPhase,
  RuntimeStatePhase,
  SessionStatus,
} from "./handle";
import type { NotebookRequest, NotebookResponse } from "./request-types";

type MissingUnionMember<Union extends string, Values extends readonly string[]> = Exclude<
  Union,
  Values[number]
>;

export const NOTEBOOK_REQUEST_TYPES = [
  "launch_kernel",
  "execute_cell",
  "execute_cell_guarded",
  "interrupt_execution",
  "shutdown_kernel",
  "run_all_cells",
  "run_all_cells_guarded",
  "send_comm",
  "apply_bokeh_session_patch",
  "get_history",
  "complete",
  "save_notebook",
  "reconcile_notebook_source",
  "clone_as_ephemeral",
  "sync_environment",
  "approve_trust",
  "approve_project_environment",
  "get_doc_bytes",
  "create_blob_upload",
  "complete_blob_upload",
  "abort_blob_upload",
] as const satisfies readonly NotebookRequest["type"][];

export const NOTEBOOK_REQUEST_TYPES_EXHAUSTIVE: MissingUnionMember<
  NotebookRequest["type"],
  typeof NOTEBOOK_REQUEST_TYPES
> extends never
  ? true
  : never = true;

export const NOTEBOOK_RESPONSE_RESULTS = [
  "kernel_launched",
  "kernel_already_running",
  "cell_queued",
  "execution_id_rejected",
  "interrupt_sent",
  "kernel_shutting_down",
  "no_kernel",
  "guard_rejected",
  "all_cells_queued",
  "notebook_saved",
  "notebook_already_current",
  "notebook_save_blocked",
  "notebook_source_reconciled",
  "notebook_source_reconciliation_blocked",
  "save_error",
  "notebook_cloned",
  "ok",
  "error",
  "history_result",
  "completion_result",
  "bokeh_session_patch",
  "sync_environment_complete",
  "sync_environment_failed",
  "doc_bytes",
  "blob_stored",
  "blob_upload_created",
  "blob_part_stored",
  "blob_upload_aborted",
  "blob_upload_error",
] as const satisfies readonly NotebookResponse["result"][];

export const NOTEBOOK_RESPONSE_RESULTS_EXHAUSTIVE: MissingUnionMember<
  NotebookResponse["result"],
  typeof NOTEBOOK_RESPONSE_RESULTS
> extends never
  ? true
  : never = true;

export type SessionControlMessage = { type: "sync_status" } & SessionStatus;

export const SESSION_CONTROL_TYPES = [
  "sync_status",
] as const satisfies readonly SessionControlMessage["type"][];

export const NOTEBOOK_DOC_PHASES = [
  "pending",
  "syncing",
  "interactive",
] as const satisfies readonly NotebookDocPhase[];

export const NOTEBOOK_DOC_PHASES_EXHAUSTIVE: MissingUnionMember<
  NotebookDocPhase,
  typeof NOTEBOOK_DOC_PHASES
> extends never
  ? true
  : never = true;

export const RUNTIME_STATE_PHASES = [
  "pending",
  "syncing",
  "ready",
] as const satisfies readonly RuntimeStatePhase[];

export const RUNTIME_STATE_PHASES_EXHAUSTIVE: MissingUnionMember<
  RuntimeStatePhase,
  typeof RUNTIME_STATE_PHASES
> extends never
  ? true
  : never = true;

export const INITIAL_LOAD_PHASES = [
  "not_needed",
  "streaming",
  "ready",
  "failed",
] as const satisfies readonly InitialLoadPhase["phase"][];

export const INITIAL_LOAD_PHASES_EXHAUSTIVE: MissingUnionMember<
  InitialLoadPhase["phase"],
  typeof INITIAL_LOAD_PHASES
> extends never
  ? true
  : never = true;

export const DISPLAY_CAPABLE_JUPYTER_OUTPUT_TYPES = ["execute_result", "display_data"] as const;

export type DisplayCapableJupyterOutputType = (typeof DISPLAY_CAPABLE_JUPYTER_OUTPUT_TYPES)[number];

export interface DisplayCapableJupyterOutput {
  output_type: DisplayCapableJupyterOutputType;
  data: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  execution_count?: number | null;
  display_id?: string;
}

export function isDisplayCapableJupyterOutputType(
  outputType: unknown,
): outputType is DisplayCapableJupyterOutputType {
  return outputType === "execute_result" || outputType === "display_data";
}

export function isDisplayCapableJupyterOutput<T extends { output_type: unknown }>(
  output: T,
): output is Extract<T, { output_type: DisplayCapableJupyterOutputType }>;
export function isDisplayCapableJupyterOutput(
  output: unknown,
): output is DisplayCapableJupyterOutput;
export function isDisplayCapableJupyterOutput(
  output: unknown,
): output is DisplayCapableJupyterOutput {
  return (
    typeof output === "object" &&
    output !== null &&
    isDisplayCapableJupyterOutputType((output as { output_type?: unknown }).output_type)
  );
}

export function isInitialLoadFailed(
  initialLoad: InitialLoadPhase,
): initialLoad is Extract<InitialLoadPhase, { phase: "failed" }> {
  return initialLoad.phase === "failed";
}

export function isInitialLoadStreaming(
  initialLoad: InitialLoadPhase,
): initialLoad is Extract<InitialLoadPhase, { phase: "streaming" }> {
  return initialLoad.phase === "streaming";
}
