// @generated by cargo run -p notebook-protocol --bin generate-runtimed-types
// Do not edit by hand.

import type { QueueEntry } from "./runtime-state";

export interface GuardedNotebookProvenance {
  observed_heads: string[];
}

export interface DependencyGuard {
  observed_heads: string[];
}

export type PackageManager = "uv" | "conda" | "pixi" | (string & {});

export type EnvSource =
  | `${PackageManager}:prewarmed`
  | `${PackageManager}:inline`
  | "uv:pyproject"
  | "pixi:toml"
  | "conda:env_yml"
  | `${PackageManager}:pep723`
  | "deno"
  | (string & {});

export type LaunchSpec = "auto" | "" | "prewarmed" | `auto:${PackageManager}` | EnvSource;

export interface FeatureFlags {
  bootstrap_dx?: boolean;
}

export interface DenoLaunchedConfig {
  permissions: string[];
  import_map?: string | null;
  config?: string | null;
  flexible_npm_imports: boolean;
}

export interface LaunchedEnvConfig extends FeatureFlags {
  uv_deps?: string[] | null;
  conda_deps?: string[] | null;
  conda_channels?: string[] | null;
  pixi_deps?: string[] | null;
  pixi_toml_deps?: string[] | null;
  pixi_toml_path?: string | null;
  pyproject_path?: string | null;
  environment_yml_path?: string | null;
  environment_yml_deps?: string[] | null;
  deno_config?: DenoLaunchedConfig | null;
  venv_path?: string | null;
  python_path?: string | null;
  launch_id?: string | null;
  prewarmed_packages?: string[];
}

export interface CommBufferRef {
  index: number;
  blob: string;
  size: number;
  media_type?: string | null;
}

export interface CommRequestMessage {
  header: Record<string, unknown>;
  parent_header?: Record<string, unknown> | null;
  metadata?: Record<string, unknown>;
  content: Record<string, unknown>;
  buffers: number[][];
  buffer_refs?: CommBufferRef[];
  channel: string;
}

export interface BokehSessionBufferRef {
  id: string;
  blob: string;
  size: number;
  media_type: string;
}

export interface BokehSessionPatchRequest {
  session_id: string;
  transaction_id: string;
  base_revision: number;
  patch: Record<string, unknown>;
  buffers?: Array<{ id: string; data: number[] }>;
  buffer_refs?: BokehSessionBufferRef[];
}

export type BokehSessionPatchReply =
  | { status: "accepted"; session_id: string; transaction_id: string; revision: number }
  | { status: "stale"; session_id: string; transaction_id: string; revision: number }
  | {
      status: "error";
      session_id: string;
      transaction_id: string;
      revision?: number | null;
      error: string;
    };

export interface BlobUploadPart {
  part_number: number;
  sha256: string;
  size: number;
}

export type NotebookRequest =
  | {
      type: "launch_kernel";
      kernel_type: string;
      env_source: LaunchSpec;
      notebook_path?: string | null;
    }
  | { type: "execute_cell"; cell_id: string; execution_id?: string | null }
  | {
      type: "execute_cell_guarded";
      cell_id: string;
      execution_id?: string | null;
      observed_heads: string[];
    }
  | { type: "interrupt_execution" }
  | { type: "shutdown_kernel" }
  | { type: "run_all_cells"; cell_execution_ids?: Record<string, string> | null }
  | {
      type: "run_all_cells_guarded";
      cell_execution_ids?: Record<string, string> | null;
      observed_heads: string[];
    }
  | { type: "send_comm"; message: CommRequestMessage }
  | { type: "apply_bokeh_session_patch"; request: BokehSessionPatchRequest }
  | {
      type: "get_history";
      /** Glob-style pattern to match. null for no filter. */
      pattern: string | null;
      /** Maximum number of entries to return. */
      n: number;
      /** Deduplicate identical entries when true. */
      unique: boolean;
    }
  | { type: "complete"; code: string; cursor_pos: number }
  | {
      type: "save_notebook";
      /** Format code cells before writing to disk. */
      format_cells: boolean;
      /** Target path. Omit or null to save in place. */
      path?: string | null;
    }
  | { type: "clone_as_ephemeral"; source_notebook_id: string }
  | { type: "sync_environment"; guard?: DependencyGuard | null }
  | { type: "approve_trust"; observed_heads?: string[] | null }
  | { type: "approve_project_environment"; project_file_path?: string | null }
  | { type: "get_doc_bytes" }
  | {
      type: "create_blob_upload";
      media_type: string;
      size: number;
      sha256?: string | null;
      part_size?: number | null;
      purpose?: string | null;
    }
  | { type: "complete_blob_upload"; upload_id: string; parts: BlobUploadPart[] }
  | { type: "abort_blob_upload"; upload_id: string };

/** One entry returned by `get_history`. */
export interface HistoryEntry {
  session: number;
  line: number;
  source: string;
}

/** One item returned in a `completion_result`. */
export interface CompletionItem {
  label: string;
  kind?: string | null;
  detail?: string | null;
  source?: string | null;
}

export type ExecutionIdRejectionReason = "malformed" | "already_exists" | "duplicate_in_request";

export type NotebookResponse =
  | {
      result: "kernel_launched";
      kernel_type: string;
      env_source: EnvSource;
      launched_config: LaunchedEnvConfig;
    }
  | {
      result: "kernel_already_running";
      kernel_type: string;
      env_source: EnvSource;
      launched_config: LaunchedEnvConfig;
    }
  | { result: "cell_queued"; cell_id: string; execution_id: string }
  | {
      result: "execution_id_rejected";
      execution_id: string;
      reason: ExecutionIdRejectionReason;
    }
  | { result: "interrupt_sent" }
  | { result: "kernel_shutting_down" }
  | { result: "no_kernel" }
  | { result: "guard_rejected"; reason: string }
  | { result: "all_cells_queued"; queued: QueueEntry[] }
  | { result: "notebook_saved"; path: string }
  | { result: "save_error"; error: SaveErrorKind }
  | { result: "notebook_cloned"; notebook_id: string; working_dir?: string | null }
  | { result: "ok" }
  | { result: "error"; error: string }
  | { result: "history_result"; entries: HistoryEntry[] }
  | {
      result: "completion_result";
      items: CompletionItem[];
      cursor_start: number;
      cursor_end: number;
    }
  | { result: "bokeh_session_patch"; reply: BokehSessionPatchReply }
  | { result: "sync_environment_complete"; synced_packages: string[] }
  | { result: "sync_environment_failed"; error: string; needs_restart: boolean }
  | { result: "doc_bytes"; bytes: number[] }
  | { result: "blob_stored"; hash: string; size: number; media_type: string }
  | { result: "blob_upload_created"; upload_id: string; part_size: number; expires_at: string }
  | { result: "blob_part_stored"; upload_id: string; part_number: number; sha256: string }
  | { result: "blob_upload_aborted"; upload_id: string }
  | { result: "blob_upload_error"; reason: BlobUploadErrorKind };

/**
 * Structured save failures returned in `NotebookResponse::SaveError`.
 * Mirrors `notebook_protocol::protocol::SaveErrorKind`.
 */
export type SaveErrorKind =
  | {
      type: "path_already_open";
      /** UUID of the room that currently holds this path. */
      uuid: string;
      /** The conflicting path. */
      path: string;
    }
  | { type: "io"; message: string };

export type BlobUploadErrorKind =
  | { kind: "size_mismatch" }
  | { kind: "hash_mismatch" }
  | { kind: "over_cap" }
  | { kind: "too_many_in_flight" }
  | { kind: "invalid_header" }
  | { kind: "unknown_upload" }
  | { kind: "part_size_mismatch" }
  | { kind: "part_hash_mismatch" }
  | { kind: "duplicate_part_conflict" }
  | { kind: "manifest_mismatch" }
  | { kind: "final_hash_mismatch" }
  | { kind: "over_peer_budget" }
  | { kind: "session_expired" }
  | { kind: "forbidden" }
  | { kind: "io"; message: string };

export type BlobDurability = "durable" | "ephemeral";
