// @generated by cargo run -p notebook-protocol --bin generate-runtimed-types
// Do not edit by hand.

/**
 * Connection-scope capability lattice generated from
 * `nteract_identity::ConnectionScope`.
 *
 * This is the single source of truth for what each scope may do on a
 * notebook room connection. The hosted room (Cloudflare Worker) and any
 * TypeScript client must use these predicates instead of hand-rolled
 * scope checks so they cannot drift from the daemon's Rust enforcement.
 */
export type ConnectionScope = "viewer" | "editor" | "runtime_peer" | "owner";

/** Every scope, in privilege order. */
export const CONNECTION_SCOPES = [
  "viewer",
  "editor",
  "runtime_peer",
  "owner",
] as const satisfies readonly ConnectionScope[];

export function isConnectionScope(value: string | null | undefined): value is ConnectionScope {
  return (CONNECTION_SCOPES as readonly string[]).includes(value ?? "");
}

export function parseConnectionScope(value: string): ConnectionScope {
  if (isConnectionScope(value)) {
    return value;
  }
  throw new Error(`unknown connection scope: ${value}`);
}

/** Whether this scope can send NotebookDoc changes. */
export function allowsNotebookWrite(scope: ConnectionScope): boolean {
  return scope === "editor" || scope === "owner";
}

/** Whether this scope can send RuntimeStateDoc changes. */
export function allowsRuntimeStateWrite(scope: ConnectionScope): boolean {
  return scope === "runtime_peer";
}

/** Whether this scope can upload blobs on hosted room connections (PUT_BLOB frames and multipart upload requests). */
export function allowsBlobUpload(scope: ConnectionScope): boolean {
  return scope === "runtime_peer" || scope === "owner";
}

/** Whether this scope can submit execution requests (owner-only until an explicit execute capability exists). */
export function allowsExecutionRequestSubmit(scope: ConnectionScope): boolean {
  return scope === "owner";
}

/** Whether this scope can publish revisions. */
export function allowsPublish(scope: ConnectionScope): boolean {
  return scope === "owner";
}

/** Whether this scope can manage ACLs. */
export function allowsAclMutation(scope: ConnectionScope): boolean {
  return scope === "owner";
}
