// @generated by cargo run -p notebook-protocol --bin generate-runtimed-types
// Do not edit by hand.

/**
 * Frame type constants generated from `notebook_wire::frame_types`.
 *
 * These correspond to the first byte of each typed frame payload on
 * notebook sync connections.
 */
export const FrameType = {
  AUTOMERGE_SYNC: 0x00,
  REQUEST: 0x01,
  RESPONSE: 0x02,
  BROADCAST: 0x03,
  PRESENCE: 0x04,
  RUNTIME_STATE_SYNC: 0x05,
  COMMS_DOC_SYNC: 0x09,
  COMMENTS_DOC_SYNC: 0x0a,
  POOL_STATE_SYNC: 0x06,
  SESSION_CONTROL: 0x07,
  PUT_BLOB: 0x08,
} as const;

export type FrameTypeName = keyof typeof FrameType;
export type FrameTypeValue = (typeof FrameType)[FrameTypeName];

/** Absolute maximum typed-frame payload size, from `notebook_wire::MAX_FRAME_SIZE`. */
export const MAX_FRAME_SIZE = 104857600;

/** Maximum control-frame payload size, from `notebook_wire::MAX_CONTROL_FRAME_SIZE`. */
export const MAX_CONTROL_FRAME_SIZE = 65536;

export interface FrameSizeLimits {
  /** Hard payload cap in bytes. Frames larger than this should be rejected. */
  cap: number;
  /** Soft payload threshold in bytes. Frames larger than this should be logged. */
  warn: number;
}

/** Per-type body cap and warn threshold generated from `notebook_wire::frame_size_limits`. */
export const FRAME_SIZE_LIMITS = {
  [FrameType.AUTOMERGE_SYNC]: { cap: 67108864, warn: 16777216 },
  [FrameType.REQUEST]: { cap: 16777216, warn: 262144 },
  [FrameType.RESPONSE]: { cap: 67108864, warn: 16777216 },
  [FrameType.BROADCAST]: { cap: 16777216, warn: 4194304 },
  [FrameType.PRESENCE]: { cap: 4096, warn: 1024 },
  [FrameType.RUNTIME_STATE_SYNC]: { cap: 67108864, warn: 16777216 },
  [FrameType.COMMS_DOC_SYNC]: { cap: 67108864, warn: 16777216 },
  [FrameType.COMMENTS_DOC_SYNC]: { cap: 67108864, warn: 16777216 },
  [FrameType.POOL_STATE_SYNC]: { cap: 1048576, warn: 262144 },
  [FrameType.SESSION_CONTROL]: { cap: 1048576, warn: 262144 },
  [FrameType.PUT_BLOB]: { cap: 33554432, warn: 8388608 },
} as const satisfies Readonly<Record<FrameTypeValue, FrameSizeLimits>>;

/** Return the payload size limits for a typed notebook frame. */
export function frameSizeLimits(frameType: number): FrameSizeLimits {
  return (
    FRAME_SIZE_LIMITS[frameType as FrameTypeValue] ?? {
      cap: MAX_FRAME_SIZE,
      warn: Math.floor(MAX_FRAME_SIZE / 2),
    }
  );
}
