name = "nteract-notebook-cloud-outputs"
main = "./src/output-document-worker.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "preview.runtusercontent.com", custom_domain = true }]

[assets]
directory = "./dist-output-document"
binding = "ASSETS"
