[package]
name = "mcp-transport"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rmcp = { workspace = true, features = ["server"] }
tokio-util = "0.7"
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
