// @flow

// Generated by `lerna ls --json`
//
// With new packages, we'll want to run this again, and add to ignores
// Instead of opting for a fully discovered setup from the monorepo, I've opted
// for this package to work when used outside of the monorepo.

module.exports = {
  lernaModules: [
    {
      name: "@nteract/commutable",
      version: "6.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/connected-components",
      version: "5.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/core",
      version: "9.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/editor",
      version: "8.0.0-alpha.0",
      private: false,
    },
    {
      name: "@mybinder/host-cache",
      version: "1.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/messaging",
      version: "5.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/monaco-editor",
      version: "2.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/notebook-app-component",
      version: "4.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/presentational-components",
      version: "2.0.0-alpha.0",
      private: false,
    },
    {
      name: "rx-binder",
      version: "3.0.0-alpha.0",
      private: false,
    },
    {
      name: "rx-jupyter",
      version: "4.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/selectors",
      version: "1.0.0",
      private: false,
    },
    {
      name: "@nteract/styleguide-components",
      version: "0.1.4",
      private: false,
    },
    {
      name: "@nteract/types",
      version: "1.0.0",
      private: false,
    },
    {
      name: "@nteract/webpack-configurator",
      version: "2.0.0-alpha.0",
      private: false,
    },
    {
      name: "@nteract/stateful-components",
      version: "1.0.0",
      private: false,
    },
    {
      name: "@nteract/mythic-notifications",
      version: "0.1.0",
      private: false,
    },
    {
      name: "@nteract/mythic-configuration",
      version: "0.1.0",
      private: false
    },
    {
      name: "@nteract/mythic-multiselect",
      version: "0.1.0",
      private: false
    },
    {
      name: "@nteract/mythic-rtc",
      version: "0.1.0",
      private: false
    },
    {
      name: "@nteract/myths",
      version: "0.1.0",
      private: false,
    },
    {
      name: "@nteract/web",
      version: "1.0.0",
      private: false,
    },
  ],
};
